// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZZnZEc0qaBcnEyEz7GN6DLXOYHkQWMo',
    appId: '1:571787890194:web:9a89759385c15e0c50d2cb',
    messagingSenderId: '571787890194',
    projectId: 'tozbi-counter',
    authDomain: 'tozbi-counter.firebaseapp.com',
    storageBucket: 'tozbi-counter.appspot.com',
    measurementId: 'G-8JH4WBXKPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYzn3-9XpXLlHR3k9x_RLJ-YOnPXFb4A',
    appId: '1:571787890194:android:150273fe82728b6450d2cb',
    messagingSenderId: '571787890194',
    projectId: 'tozbi-counter',
    storageBucket: 'tozbi-counter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIHFEyzZk9rbpkzd-GncwWCgx3QMV0zc',
    appId: '1:571787890194:ios:d0b2a24e9694ca6d50d2cb',
    messagingSenderId: '571787890194',
    projectId: 'tozbi-counter',
    storageBucket: 'tozbi-counter.appspot.com',
    androidClientId: '571787890194-jdas96i8clvs9a3899em58d9oa08mvdp.apps.googleusercontent.com',
    iosClientId: '571787890194-18j8coev00su7gu3hsqnqd354mdhro4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.sound',
  );
}
